//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exo7
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableStagiaire
    {
        public int NumOsiaStagiaire { get; set; }
        public string NomStagiaire { get; set; }
        public string PrenomStagiaire { get; set; }
        public string RueStagiaire { get; set; }
        public string VilleStagiaire { get; set; }
        public string CodePostalStagiaire { get; set; }
        public Nullable<int> NbreNotesStagiaire { get; set; }
        public Nullable<int> PointsNotesStagiaire { get; set; }
    }
}
