//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exo7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_1
    {
        public int numOsiaStagiaire { get; set; }
        public string nomStagiaire { get; set; }
        public string prenomStagiaire { get; set; }
        public string rueStagiaire { get; set; }
        public string villeStagiaire { get; set; }
        public string codePostalStagiaire { get; set; }
        public Nullable<int> nbreNotesStagiaire { get; set; }
        public Nullable<int> pointsNotesStagiaire { get; set; }
    }
}
